controller_list:
  - name: fake_mycobot_280_gazebo_controller
    type: $(arg fake_execution_type)
    joints:
      - joint2_to_joint1
      - joint3_to_joint2
      - joint4_to_joint3
      - joint5_to_joint4
      - joint6_to_joint5
      - joint6output_to_joint6
initial:  # Define initial robot poses.
  - group: mycobot_280_gazebo
    pose: HOME